export default{

    onboardingScreen1: require('../assets/images/onboarding/onboarding_screen1.png'),
    onboardingScreen2: require('../assets/images/onboarding/onboarding_screen2.png'),
    onboardingScreen3: require('../assets/images/onboarding/onboarding_screen3.png'),
    onboardingScreen4: require('../assets/images/onboarding/onboarding_screen4.png'),
    logo1: require('../assets/images/logo/logo1.png'),
    userIcon:require('../assets/images/logo/profile.png'),
    helpIcon:require('../assets/images/icons/HELP.png'),
    walletIcon:require('../assets/images/icons/WALLET.png'),
    settingsIcon:require('../assets/images/icons/SETTINGS.png'),
    historyIcon:require('../assets/images/icons/HISTORY.png'),
    learnIcon:require('../assets/images/icons/LEARN.png'),
    logoutIcon:require('../assets/images/icons/LOGOUT.png'),
    profileIconWhite:require('../assets/images/icons/USER.png'),
    editEmailIcon:require('../assets/images/icons/email.png'),
    editEmailIconWhite:require('../assets/images/icons/emailWhite.png'),
    editPasswordIcon:require('../assets/images/icons/ResetPassword.png'),
    editPasswordIconWhite:require('../assets/images/icons/ResetPasswordWhite.png'),
    editProfileIcon:require('../assets/images/icons/editProfile.png'),
    profileIcon:require('../assets/images/icons/profile.png'),
    applicationStatusIcon:require('../assets/images/icons/status.png'),
    redDotIcon:require('../assets/images/icons/redDot.png'),
    hamburgerIcon:require('../assets/images/icons/hamburger.png'),
    gpsIcon:require('../assets/images/icons/gps.png'),
    ambulanceIcon:require('../assets/images/icons/AMB.png'),
    policeIcon:require('../assets/images/icons/POLICE.png'),
    fireBrigadeIcon:require('../assets/images/icons/FIREBRIGADE.png'),
    messageGreenIcon:require('../assets/images/icons/MESSAGING2.png'),
    sendIcon:require('../assets/images/icons/SEND.png'),
    distanceIcon:require('../assets/images/icons/distance.png'),
    timerIcon:require('../assets/images/icons/timer.png'),
    ambulanceTrackIcon:require('../assets/images/icons/AmbulanceTrack.png'),
    splashScreen:require('../assets/images/logo/splashScreen.jpeg'),
}