export default {
    LOGIN:"Login",
    SIGNUP:'Sign Up',
    ENTER_EMAIL_ADDRESS:"Enter email address",
    ENTER_PASSWORD:"Enter your password",
    CONFIRM_PASSWORD:"Confirm your password",
    EMAIL_REQUIRED:"Email is required",
    PASSWORD_REQUIRED:"Password is required",
    CONFIRM_PASSWORD_REQUIRED:"Confirm password is required",
    EMAIL_INVALID:"Email is invalid",
    PASSWORD_INVALID:"Password must contain at least one uppercase, one lowercase, one number and one special character",
    CONFIRM_PASSWORD_INVALID:'Password dit not match',
    FORGOT_PASSWORD:"Forget password?",
    HAVENT_REGESTER_YET:'Havent Register Yet?',
    SAFE_CITIZENS_LIFE:"Safe Citizens Life",
    FIRST_NAME_REQUIRED:"First name is required",
    LAST_NAME_REQUIRED:"Last name is required",
    PHONE_NUMBER_REQUIRED:"Phone number is required",
    PHONE_NUMBER_INVALID:"Phone number is invalid. ex-0312-1234567",
    ADDRESS_REQUIRED:"Address is required",
    CITY_REQUIRED:"City is required",
    FIRST_NAME_INVALID:"First name is invalid",
    LAST_NAME_INVALID:"Last name is invalid",
    ADDRESS_INVALID:"Address is invalid",
    CITY_INVALID:"City is invalid",
    BLOOD_GROUP_REQUIRED:"Blood group is required",
    BLOOD_GROUP_INVALID:"Blood group is invalid",
    COUNTRY_REQUIRED:"Country is required",
    COUNTRY_INVALID:"Country is invalid",
    IMAGE_REQUIRED:"Image is required",
    ENTER_FIRST_NAME:"Enter first name",
    ENTER_LAST_NAME:"Enter last name",
    ENTER_PHONE_NUMBER:"Enter phone number",
    ENTER_ADDRESS:"Enter address",
    ENTER_CITY:"Enter city",
    ENTER_BLOOD_GROUP:"Enter blood group",
    ENTER_COUNTRY:"Enter country",
    UPLOAD_IMAGE:"Upload image",
    GENDER_REQUIRED:'Please select gender',
    ENTER_CNIC:'Enter cnic number',
    CNIC_REQUIRED:'Cnic is required',
    CNIC_INVALID:'Cnic is invalid',
    ALREADY_REGISTER:'Already Register?',
    SIGNIN:'Sign In',
    ENTER_GENDER:'Enter Gender',
    DROWSINESS_DETECTION:'Drowsiness Detection',
    COLLISION_DETECTION:'Collison Detection',
    RESPONDER_LIVE_TRACKING:'Responder live tracking',
    INCIDENT_REPORTING:'Incident Reporting',
    SAFE_CITIZENS_LIFE_APPLICATION:'Safe Citizens Life Application',
    PROVIDES_YOU_A_DROWSINESS_DETECTION_SYSTEM_IF_YOU_GET_SLEEPY_WHILE_DRIVING:'provides you a drowsiness detection system if you get sleepy while driving.',
    IF_YOUR_CAR_GETS__INTO_AN_ACCIDENT_WE_WILL_SENT_YOU_AN_ALERT_IF_THERE_IS_NO_RESPONSE_TO_THE_ALERT_WE_WILL_COME_TO_RESCUE_YOU:'If your car gets into an accident, we will sent you an alert if there is no response to the alert, we will come to rescue you.',
    IN_CASE_OF_EMERGENCY_YOUR_LOCATION_WILL_BE_SHARED_WITH_NEAREST_RESPONDER_AND_RESPONDER_WILL_BE_DIRECTED_TO_RESCUE_YOU:'In case of emergency, your location will be shared with nearest responder and responder will be directed to rescue you.',
    IF_YOU_WITNESS_AN_ACCIDENT_JUST_SHARE_THE_PICTURE_OUR_AI_SYSTEM_WILL_DETECT_THE_ACCIDENT_AND_SHARE_THE_LOCATION:'If you witness an accident, just share the picture, our AI system will detect the accident and share the location.',
    CONTINUE:'Continue',
    SEND_RECOVERY_LINK:'Send Recovery Link',
    BACK:'Back',
    RECOVER_PASSWORD:'Recover Password',
    LOGOUT:'Logout',
    HISTORY:'History',
    SETTINGS:'Settings',
    WALLET:'Wallet',
    LEARN_TRAFFIC_RULES:'Learn Traffic Rules',
    HELP:'Help',
    ABOUT:'About',
    USER_PROFILE:'User Profile',
    FIRST_NAME:'First Name',
    LAST_NAME:'Last Name',
    PHONE_NUMBER:'Phone Number',
    ADDRESS:'Address',
    CITY:'City',
    BLOOD_GROUP:'Blood Grp',
    COUNTRY:'Country',
    DATE_OF_BIRTH:'Date of Birth',
    GENDER:'Gender',
    EMAIL:'Email',
    CNIC:'Cnic',
    ADDRESS:'Address',
    PROFILE:'Profile',
    SAVE:'Save',
    EDIT_EMAIL:'Edit Email',
    EDIT_PASSWORD:'Edit Password',
    EDIT_PROFILE:'Edit Profile',
    RESET_EMAIL:'Reset Email',
    RESET_PASSWORD:'Reset Password',
    ENTER_NEW_PASSWORD:'Enter new password',
    ENTER_OLD_PASSWORD:'Enter old password',
    ENTER_NEW_EMAIL_ADDRESS:'Enter new email address',
    APPLICATION_STATUS:'Application Status',
    DEAR_USER_YOUR_APPLICATION_IS_UNDER_REVIEW_YOU_WILL_GET_ACCESS_TO_THE_APPLICATION_ONCE_YOUR_APPLICATION_IS_ACCEPTED:'Dear User, Your application is under review. You will get access to the application once your application is accepted.',
    YOU_WILL_BE_NOTIFIED_VIA_EMAIL:'You will be notified via Email.',
    LIVE_MONITORING:'Live Monitoring',
    REQUEST_A_VHHECILE:'Request A vehicle',
    AMBULANCE:'Ambulance',
    FIRE_BRIGADE:'Fire Brigade',
    POLICE:'Police',
    DATE_REQUIRED:'Date Required',
    D_O_B:'D.O.B',
    SUCCESSFULLY_APPLIED:"Successfully Applied ",
    CNIC_ALREADY_EXIST:"Cnic already exist",
    EMAIL_ALREADY_EXIST:"Email already exist",
    SUCCESSFULLY_LOGIN:"Successfully Login",
    FEEDBACK_AND_SUPPORT:"Feedback and Support",
    FEEDBACK:"Feedback",
    REPORT_A_BUG:"Report a bug",
    PRIVACY_AND_TERMS:"Privacy and Terms",
    ABOUT_US:"About Us",
    CONTACT_US:"Contact Us",
    FAQS:"FAQs",
    RATE_APP:"Rate APP",
    SHARE_APP:"Share App",
    PRIVACY_POLICY:"Privacy Policy",
    TERMS_OF_SERVICE:"Terms of Service",

}